api_doc:
    path: /api-doc
    controller: api_platform.swagger_ui.action

api_login_check:
    path: /api/login-check

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
